Login Frontend
iOS-vk-education/2022_1s_ElectronicUniversity pull request #2
Opened 2022-11-03 10:17 UTC by ArtemTin

2022-11-03 18:55 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Views/AuthView.swift
> +    // "Notification" view? Может его отдельным классом прямо?
Это будет всплывающие окно, его надо централизовать. То есть сделать базовый какой нибудь и от него наследовать все остальное

2022-11-03 18:55 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Views/AuthView.swift
> +    var bmstuImage: UIImageView = UIImageView(frame: .zero)
Весь UI - private

2022-11-03 18:55 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Views/AuthView.swift
> +    var loginField: UITextField! = UITextField(frame: .zero)
Форс анрап не юзаем, даже если очень хочется)

2022-11-03 18:55 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Views/AuthView.swift
> +    var passwordField: UITextField! = UITextField(frame: .zero)
Уточнение типа не нужно, просто  
`let passwordField = UITextField()`

2022-11-03 18:55 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Views/AuthView.swift
> +    var passwordField: UITextField! = UITextField(frame: .zero)
на let обрати внимание

2022-11-03 18:55 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Views/AuthView.swift
> +    // "loading..." view? каким классом? картинка?
Да, все классом, и вообще в контроллере не должно быть верстки(только самая минимальна, по типу прибить одну вьюху)

2022-11-03 18:55 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Views/AuthView.swift
> +    // "loading..." view? каким классом? картинка?
Или можно так 
`override loadView() {
        view = customView
}`

2022-11-03 18:55 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Views/AuthView.swift
> +//    lazy var titleLabel: UILabel = {
lazy var не нужно, просто let и в отдельной функции настраиваешь все что нужно(можно для каждой отдельно, можно единую для всех, как удобнее)

2022-11-03 18:55 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Views/AuthView.swift
> +        // тут заполняем вьюшки данными. наверное, стоит в отдельную функцию? может это вообще презентер делает?? но тут нет получения данных из модели...
ViewController только принимает данные от презента и перекидывает во view, никакой логики

2022-11-03 18:55 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Views/AuthView.swift
> +        [loginField, passwordField, loginButton, continueWithoutLoginButton].forEach { box in
Идея хорошая, но лучше вынести в отдельную вьюху и сделать стек вертикальный

2022-11-03 18:55 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Views/AuthView.swift
> +        // а вот тут позиционируем вьюшки (snapkit)
Костреинты в отдельный метод, например такой: 
`func setupConstraints()`

2022-11-03 18:55 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Views/AuthView.swift
> +    func updateView()
Тут короче ставишь презентер в контроллер, накрываешь протоколом и делаешь методы по типу onViewDidLoad  и тд, далее презентер обрабатывает и выплевывает сюда данные, которые передается как раз в аргументы

2022-11-03 18:55 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Views/LoggedView.swift
> +// кажется, он должен быть ScrollView из двух компонент: фотка пользователя и имя + список кнопок меню (твой профиль, успеваемость...)
Таблица или коллекция, лучше коллекция(у вас кстати требования для проекта - минимум одна коллекция или таблица)

2022-11-03 18:55 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +      "identity" : "snapkit",
А че не podы?

2022-11-03 18:55 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU.xcodeproj/project.pbxproj
> +		7057642529131FEE006555E2 /* SnapKit in Frameworks */ = {isa = PBXBuildFile; productRef = 7057642429131FEE006555E2 /* SnapKit */; };
все контроллеры должны быть по разным папкам + все должны оканчиваться на Controller (AuthViewController и т.д.)

2022-11-03 18:55 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU.xcodeproj/project.pbxproj
> +		7057642B29132A27006555E2 /* TabBarViewController.swift in Sources */ = {isa = PBXBuildFile; fileRef = 7057642A29132A27006555E2 /* TabBarViewController.swift */; };
Создание таб бара лучше вынести в координатор(почитай что такое, потом мне черкани есть хороший пример)

2022-11-03 18:55 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Views/AuthView.swift
> +// Вьюконтроллер, показываемый на первом запуске + на вкладке "аккаунт", если человек не вошел в аккаунт
Мне кажется лучше сделать отдельный профиль и там поставить заглушку в виде лейбла и кнопки "Войти"

2022-11-03 18:55 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Views/AuthView.swift
> +//           label.text = "Profile"
Кстати будем сразу делать строки локализации в связке с R.swift(погуглить), что в коде не было строк. И еще такой момент, когда будете верстать константы выносите из класса(над контроллером пишите и делайте их приватными). Пример: 
`private let LOGIN_HEIGHT: CGFloat = 27`

2022-11-09 21:59 UTC, ArtemTin commented on Graal-BMSTU/Graal-BMSTU/TabBar/View/TabBarView.swift
> +        viewControllers = [
Почему после добавления вьюконтроллеров вкладок их top для снапкита - верх экрана, а не позиция под названием вкладки?
<img width="354" alt="Снимок экрана 2022-11-10 в 00 59 32" src="https://user-images.githubusercontent.com/60343664/200950905-60d19d21-9dea-4975-b73d-ccda1faca2a8.png">

2022-11-10 09:47 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/Model/AuthModel.swift
> +struct User
Это в отдельный файл

2022-11-10 09:47 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/Model/AuthModel.swift
> +    func authenticate(login: String, password: String, callback: (User?) -> Void)
Обычно называют completion, а не callback + это должно быть сбегающие замыкание
Я бы еще подставил `typalias AuthClosure = (User?) -> Void` и туда запихал [Result](https://developer.apple.com/documentation/swift/result) для обработки ошибок. А вообще если че async/await с 13 аськи поддерживается, так что можно его попробовать

2022-11-10 09:47 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/Presenter/AuthPresenter.swift
> +class AuthViewPresenter
Пиши final, это нужно для ускорении работы класса. Если интересно почитай про диспетчеризацию

2022-11-10 09:47 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/Presenter/AuthPresenter.swift
> +import UIKit
В презентере не должно быть упоминания UIkit

2022-11-10 09:47 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +    private let bmstuImage = UIImageView(frame: .zero)
В отдельную вьюху, не верстай в контроллере

2022-11-10 09:47 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +    private let authViewPresenter = AuthViewPresenter(authService: AuthService())
Это зависимость, она проставляется из вне

2022-11-10 09:47 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +        authViewPresenter.setup()
Смотри, по поводу презентра, давай сделаем так: Сделай протокол `AuthPresenter`, и на него подпиши свой текущий презентер(назови его `AuthPresenterImpl`). В протоколе пропиши все методы, которые тебе нужны (например onVIewDidload, authenticate и тд). Реализуй их в презентере. Далее убираешь делегат и через колбеки от вьюхи в контроллере проставляешь вызовы из презентера(делегат иногда мешает при переиспользовании вьюх)

2022-11-10 09:47 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +        authViewPresenter.authenticate(username: loginField.text ?? "", password: passwordField.text ?? "")
И да, в дополнение к моменту выше. Во вьюхе сделай замыкания по типу 
`private var loginAction: EmptyClosure?` - EmptyClosure это замыкание вида () -> Void (typealias)
Вызывай их в этой функции(только которая будет во вьюхе). Проставляй замыкания через 
`func setLoginAction(_  action: @escaping EmptyClosure) {
           self.loginAction = action
}`

2022-11-10 09:47 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +    func setupConstraints()
Вся настройка UI приватная

2022-11-10 09:47 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +    func displaySuccessNotification(user: User?)
Модель не должна быть видна в контроллере

2022-11-10 09:47 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +        loginField.placeholder = R.string.localizable.welcome()
В отдельную функции(сделай чтоб все сходилось в одну `setupUI()` и вызови тут)

2022-11-10 09:47 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +    func setupConstraints()
И в целом сделать лучше private extension и там делать настройку

2022-11-10 09:47 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +class AuthViewController: UIViewController, AuthViewDelegate {
final

2022-11-10 09:47 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/SceneDelegate.swift
> +        window = UIWindow(frame: windowScene.screen.bounds)
Давай вынесем это в [координатор](https://github.com/Grandschtien/PartyPoint/tree/develop/PartyPoint/PartyPoint/Application/Coordinators)

2022-11-10 09:47 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/TabBar/View/TabBarView.swift
> +        viewControllers = [
Крепи к safeArea

2022-11-10 09:47 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/TabBar/View/TabBarView.swift
> +class TabBarViewController: UITabBarController
Это в целом лишнее, вам достаточно дефолтного UITabBarController

2022-11-10 09:47 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/TabBar/View/TabBarView.swift
> +class TabBarViewController: UITabBarController
Чеки комент к координатору

2022-11-10 09:47 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ru.lproj/Localizable.strings
> +"Welcome" = "Здравствуйте";
с маленькой буквы + через snack_case

2022-11-10 09:47 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ru.lproj/Localizable.strings
> +"Welcome" = "Здравствуйте";
Название имеется в виду

2022-11-11 09:17 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/Presenter/AuthPresenter.swift
> +    weak var viewController: AuthViewControllerPr?
Лучше не pr, а protocol)

2022-11-11 09:18 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/Presenter/AuthPresenter.swift
> +        authService.authenticate(login: username ?? "", password: password ?? "")
Оператор "??" сильно замедляет сборку проекта, старайся его не очень часто юзать лучше через `guard`

2022-11-11 09:20 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +protocol AuthPresenter
Все протоколы в отдельный файл, искать потом будет трудно

2022-11-11 09:20 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +protocol AuthViewControllerPr: AnyObject
Тоже самое

2022-11-11 09:22 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +            make.size.equalTo(CGSize(width: 100, height: 100))
CGSize не нужен, просто 300. Ток учитывай, что это может съехать на айфоне 7, например

2022-11-11 09:23 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/TabBar/View/TabBarView.swift
> +        authPr.viewController = (viewControllers?[0] as? UINavigationController)?.viewControllers[0] as? AuthViewController
Вот эта штука будет собираться одна секунд 10-20, давай разобьем на более мелкие составляющие

2022-11-11 09:24 UTC, ArtemTin commented on Graal-BMSTU/Graal-BMSTU/TabBar/View/TabBarView.swift
> +        authPr.viewController = (viewControllers?[0] as? UINavigationController)?.viewControllers[0] as? AuthViewController
то есть это в принципе не плохо? я думал, это в билдер будет засовываться?

2022-11-11 09:24 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> -class AuthViewController: UIViewController, AuthViewDelegate {
Отдельный Файл

2022-11-11 09:25 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +final class AuthView: UIView
Отдельный файл

2022-11-11 09:25 UTC, ArtemTin commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +            make.size.equalTo(CGSize(width: 100, height: 100))
да, это пока просто чтобы хоть показывалось на 14 айфоне, без адаптивочки и т.п. красоты (пока делаю акцент на том, чтобы правильно связать все части из презентера, контроллера + вьюшки и данных)

2022-11-11 09:26 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +        loadView()
Это не надо тут, `loadView` вызывается до `viewDidLoad`

2022-11-11 09:26 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +        authView = AuthView()
Это можно прям в поле класса сделать

2022-11-11 09:30 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +    func setupUI()
Давай короче такое правило заведем. Вся настройка UI будет в `private extension`. Там будут методы `setupUI`, `setupConstraints`. В `setupUI` будет добавление `subviews` и настройка их, в `setupConstraints` будет настройка констреинтов и еще будет сверху //MARK: - private methods -. Все экшоны будут тоже в приватном расширении и будут помечены //MARK: - Actions -

2022-11-11 09:31 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +    func setupUI()
Это я написал, чтоб потом не путаться, тебе надо только марки проставить и все

2022-11-11 09:32 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +    func setLoginAction(_ action: @escaping LoginAction)
Эту лучше в другие расширение вынести

2022-11-11 09:33 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/TabBar/View/TabBarView.swift
> -            createNavController(for: AuthViewController(), title: R.string.localizable.accountTab(), image: UIImage(systemSymbol: .personCircle)),
Эту логику вынесем в координатор, и в целом переноси строки в длинных функциях

2022-11-11 09:34 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/TabBar/View/TabBarView.swift
> +        authPr.viewController = (viewControllers?[0] as? UINavigationController)?.viewControllers[0] as? AuthViewController
Такая строчка плохо читается, лучше разбей на несколько

2022-11-26 10:00 UTC, Grandschtien requested changes

2022-11-26 10:00 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
>  import Rswift
Эту не нужно тут + в снепе уже есть UIkit, можно убрать

2022-11-26 10:00 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
>      func authenticate(login: String?, password: String?)
Все протоколы в отдельный файл

2022-11-26 10:00 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +final class AuthViewController: UIViewController, AuthViewControllerPr {
Почему наследуется от AuthViewControllerPr? Это же протокол презента

2022-11-26 10:00 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +        authView = AuthView()
Не забыть

2022-11-26 10:00 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +final class AuthView: UIView {
Это в AuthView, контроллер в AuthViewController

2022-11-26 10:00 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +final class AuthView: UIView {
*Название файлов

2022-11-26 10:00 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +    private let passwordField = UITextField(frame: CGRect(x: 5, y:70, width: 300, height: 70))
Зачем фрейм? У нас констреинты

2022-11-26 10:00 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +            action(loginField.text, passwordField.text)
проверка не нужна, сделай action?(loginField.text, passwordField.text) и назови более понятно (название должно давать понимание что делает этот экшен)

2022-11-26 10:00 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +    @objc private func logoutButtonPressed() {
Это в отдельный private extension

2022-11-26 10:00 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +extension AuthView {
тут private

2022-11-26 10:00 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
>      private func createLoginButton() -> UIButton {
Тут не нужно тогда private

2022-11-26 10:00 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +        /*loginButtonConfig.buttonSize = .large
убрать все лишние коменты

2022-11-26 10:00 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +        //loginField.borderStyle = UITextField.BorderStyle.roundedRect
убрать все лишние коменты

2022-11-26 10:00 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthView/View/AuthView.swift
> +        loginButton = createLoginButton()
В поле класса сделать = UIButton, в функции настрой

2022-11-28 08:23 UTC, Grandschtien commented
Я чет запутался, че в этой ветке сейчас?

2022-12-02 20:29 UTC, Grandschtien requested changes

2022-12-02 20:29 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthScreen/AuthView.swift
> +        if let action = self.loginAction {
Эта проверка не нужна, просто `loginAction?(loginField.text, passwordField.text)`

2022-12-02 20:29 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthScreen/AuthView.swift
> +        if let action = self.skipAuthAction {
Тут тоже

2022-12-02 20:29 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthScreen/AuthView.swift
> +    func setupUI() {
Функция очень большая, читать сложно, разбей на несколько

2022-12-02 20:29 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthScreen/AuthView.swift
> +    func setupUI() {
Можно разбить на функции для каждой вьюхи

2022-12-02 20:29 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthScreen/AuthView.swift
> +        if AppCoordinator.isFirstLaunch() {
Вьюха не должна ничего знать о координаторе, во вьюхе должен говорить презентер что делать, она ничего не решает

2022-12-02 20:29 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthScreen/AuthView.swift
> +
Много лишних пробелов

2022-12-02 20:29 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthScreen/AuthView.swift
> +
И тут тоже

2022-12-02 20:29 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthScreen/AuthView.swift
> +    func loginButtonConf() {
Вот тут две кнопки почти одинаковые, вынеси в компонент

2022-12-02 20:29 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileBuilder.swift
> +    private init(viewController: ProfileViewControllerProtocol, presenter: ProfilePresenter, router: ProfileRouter) {
Длинные строки переноси

2022-12-02 20:29 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileRouter.swift
> +        placeholderLabel.text = "Profile"
Локализация

2022-12-02 20:29 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileRouter.swift
> +        placeholderLabel.text = "Settings"
Тоже локализация

2022-12-02 20:29 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileView.swift
> +// MARK: - actions setups
Ваще по хорошему пробелы после марков не нужны

2022-12-02 20:29 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileView.swift
> +        elems.forEach {
можно не делать переменную, просто через точку и вместо box `$0`

2022-12-02 20:29 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileView.swift
> +        elems.forEach {
Давай ваще в снапките будем юзать $0

2022-12-02 20:29 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileViewController.swift
> +        self.state = to
после to сделай локальную переменную по типу `func setState(toView state: ProfileViewState)`

2022-12-02 20:29 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileViewController.swift
> +        if to == .profile {
Тут switch юзай

2022-12-03 22:25 UTC, ArtemTin commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileView.swift
> +// MARK: - actions setups
У меня AppCode их ставит, можно оставить?

2022-12-05 10:51 UTC, Grandschtien approved these changes

2022-12-05 10:51 UTC, merged