Architecture rerework
iOS-vk-education/2022_1s_ElectronicUniversity pull request #3
Opened 2022-11-11 21:08 UTC by ArtemTin

не сливать до коммита Маши в login_frontend
Егор, посмотри пожалуйста. но я еще не закончил, у меня прямо много вопросов по, например, Interactor и какие протоколы за что отвечать будут (не понял это из твоего кода пока что)

2022-11-21 15:35 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Application/Coordinators/AppCoordinator.swift
> +        return UserDefaults.standard.value(forKey: "NotFirstLaunch") == nil
Давай ключ в приватную константу вынесем(за класс)

2022-11-21 15:35 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Application/Coordinators/AppCoordinator.swift
> +        return UserDefaults.standard.value(forKey: "NotFirstLaunch") == nil
И тут не умрет если будет false?

2022-11-21 15:35 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Application/Coordinators/AuthFlowCoordinator.swift
> +{
Скобку не переноси и пробелы лишние убери

2022-11-21 15:35 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Application/Coordinators/AuthFlowCoordinator.swift
> +    {
Тоже скобка

2022-11-21 15:35 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Application/Coordinators/AuthFlowCoordinator.swift
> +    var navigationController: UINavigationController
Тут не оч если честно, эти штуки не стоит давать менять извне

2022-11-21 15:35 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Application/Coordinators/MainFlowCoordinator.swift
> +    {
Скобки

2022-11-21 15:35 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Application/Coordinators/MainFlowCoordinator.swift
> +
Пробелы убирай лишние

2022-11-21 15:35 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthScreen/AuthView.swift
> +////  AuthView.swift
Лишние файлы убираем или если нужны будут, то в стеш кинь

2022-11-21 15:35 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthScreen/AuthViewController.swift
> +        authView.setLoginAction(authViewPresenter.authenticate)
Давай все приватные методы методы в экстеншен, публичные тоже

2022-11-21 15:35 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthScreen/AuthViewController.swift
> +        authView.setLoginAction(authViewPresenter.authenticate)
И `// MARK:` пометь

2022-11-21 15:35 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthScreen/AuthViewController.swift
> +    override func loadView()
перегрузки все после инитов

2022-11-21 15:35 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthScreen/AuthViewController.swift
> +        authView.setLoginAction(authViewPresenter.authenticate)
И такой момент еще, я чет не вижу где метод authenticate - протокол в котором он есть закоментирован. И разверни плез замыкание и там вызови нужный метод, а то так не оч понятно

2022-11-21 15:35 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileBuilder.swift
> +    private init(viewController: ProfileViewController, presenter: ProfilePresenter, coordinator: ProfileCoordinator)
А зачем ты на 19 строке передаешь в синит презентер, контроллер и координатор, а потом создаешь их на 29 - 31?

2022-11-21 15:35 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileCoordinator.swift
> +final class ProfileCoordinatorImpl: ProfileCoordinator
Координатор == роутер?

2022-11-21 15:35 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileModel.swift
> +struct User
В отдельный файл

2022-11-21 15:35 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfilePresenter.swift
> +    weak var vc: ProfileViewController?
давай его private сделаем и накроем протоколом, а стать будет через функцию

2022-11-21 15:35 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfilePresenter.swift
> +import UIKit
В презентере не должно быть UIkit

2022-11-21 15:35 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileViewController.swift
> +        fatalError("init(coder:) has not been implemented")
`return nil`

2022-11-21 16:43 UTC, ArtemTin commented on Graal-BMSTU/Graal-BMSTU/Application/Coordinators/AppCoordinator.swift
> +        return UserDefaults.standard.value(forKey: "NotFirstLaunch") == nil
Так если false, он запустит мейнфлоу

2022-11-21 16:44 UTC, ArtemTin commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileCoordinator.swift
> +final class ProfileCoordinatorImpl: ProfileCoordinator
да

2022-11-21 16:44 UTC, ArtemTin commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfilePresenter.swift
> +    weak var vc: ProfileViewController?
Это и есть протокол

2022-11-26 09:50 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Application/Coordinators/AppCoordinator.swift
> +        UserDefaults.standard.value(forKey: "NotFirstLaunch") == nil
Оставь лучше return, лучше читается и вынести ключи в константы приватные

2022-11-26 09:50 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Application/Coordinators/AppCoordinator.swift
> +        UserDefaults.standard.value(forKey: "NotFirstLaunch") == nil
можешь еще вынести UserDefaults в поля класса, это зависимость

2022-11-26 09:50 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Application/Coordinators/AuthFlowCoordinator.swift
> +        self.navigationController.setViewControllers([child.viewController as UIViewController], animated: false)
А зачем ты приводишь к UIViewController, этот класс и так от него наследуется

2022-11-26 09:50 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Application/Coordinators/CoordinatorsProtocols.swift
> +//protocol ScenarioCoordinator: AnyObject {
Коменты убери лишние

2022-11-26 09:50 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Application/Coordinators/MainFlowCoordinator.swift
> +//        UIView.transition(with: window, duration: 0.5, options: .transitionCrossDissolve, animations: {})
Убери комент

2022-11-26 09:50 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Application/Coordinators/MainFlowCoordinator.swift
> +            fatalError("No navigation controller for main menu tab!")
return

2022-11-26 09:50 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Application/Coordinators/MainFlowCoordinator.swift
> +        let built = UIViewController()
Это зачем? Сделай модуль сразу и создавай из контейнера

2022-11-26 09:50 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Application/Coordinators/MainFlowCoordinator.swift
> +            fatalError("No navigation controller for schedule tab!")
return

2022-11-26 09:50 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Application/Coordinators/MainFlowCoordinator.swift
> +            fatalError("No navigation controller for training tab!")
return, давай fatalError не будем оставлять

2022-11-26 09:50 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Application/Coordinators/MainFlowCoordinator.swift
> +        built.view.backgroundColor = .white
background выставляй изнутри контроллера

2022-11-26 09:50 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/AuthScreen/AuthViewController.swift
> +//
убери, если не нужно

2022-11-26 09:50 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileCoordinator.swift
>      init(window: UIWindow, navigationController: UINavigationController) {
Этот координатор - по сути роутер, лучше так его и назови. Координатор более глобальная сущность

2022-11-26 09:50 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileModel.swift
> +struct User {
в отдельный файл

2022-11-26 09:50 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileModel.swift
> +struct User {
Название файла еще как то не вяжется с тем, что в нем

2022-11-26 09:50 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfilePresenter.swift
>          let user: User? = service?.getUserData()
getUserData уже отдает опционал, можно не указывать тип

2022-11-26 09:50 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfilePresenter.swift
старайся лишние пробелы не оставлять, код так выглядит оч рвано

2022-11-26 09:50 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileProtocols.swift
> +protocol ProfileViewController: AnyObject, UIViewController {
Протокол не должен оканчиваться на "Controller", а само наследование от UIViewController вынеси в контроллер

2022-11-26 09:50 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileView.swift
>          profileDetailButton.configuration = profileDetailButtonConf()
давай это просто в функцию вынесем и не будем возвращать ничего

2022-11-26 09:50 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileView.swift
>      @objc private func profileDetailButtonPressed() {
В отдельный private extension

2022-11-26 09:50 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileView.swift
>  final class AuthView: UIView {
В отдельный файл

2022-11-26 09:50 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileView.swift
> +    private let loginButton = UIButton(frame: .zero)
Давай вынесем это в отдельную вьюху, чтоб не копировать потом для кнопки logout

2022-11-26 19:46 UTC, ArtemTin commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileBuilder.swift
> +    private init(viewController: ProfileViewController, presenter: ProfilePresenter, coordinator: ProfileCoordinator)
Так инит приватный, я в ассембле создаю презентер, контроллер и координатор, и пакую их в Builder, возвращаю его же

2022-11-26 19:48 UTC, ArtemTin commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileCoordinator.swift
>      init(window: UIWindow, navigationController: UINavigationController) {
Можно я так не буду делать? Мне легче все называть одним и тем же именем, ибо по сути они реально одинаковые действия делают. Протокол, например, можно один и тот же юзать. Или я не прав?

2022-11-26 20:18 UTC, ArtemTin commented on Graal-BMSTU/Graal-BMSTU/Application/Coordinators/MainFlowCoordinator.swift
> +        let built = UIViewController()
Это плейсхолдер, пока не написаны экран

2022-11-26 20:23 UTC, ArtemTin commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileView.swift
> +    private let loginButton = UIButton(frame: .zero)
всм копировать?

2022-11-26 20:24 UTC, ArtemTin commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileProtocols.swift
> +protocol ProfileViewController: AnyObject, UIViewController {
У меня здесь наследование, чтобы можно было приводить к этому типу

2022-11-26 20:27 UTC, ArtemTin commented on Graal-BMSTU/Graal-BMSTU/Application/Coordinators/MainFlowCoordinator.swift
> +        built.view.backgroundColor = .white
это плейсхолдер

2022-11-26 20:49 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileProtocols.swift
> +protocol ProfileViewController: AnyObject, UIViewController {
Не совсем понял, но у тебя приведется твой контроллер даже если он накрыт эти проколом

2022-11-26 20:49 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileView.swift
> +    private let loginButton = UIButton(frame: .zero)
у тебя вьюга кнопки 2 раза юзается почти одинаковая, на логине и локауте

2022-11-26 20:56 UTC, Grandschtien requested changes

2022-11-26 20:56 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileViewController.swift
>          state = .auth
это надо вынести в инит

2022-11-26 20:56 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileViewController.swift
>          state = .auth
В аргументы инита*

2022-11-26 20:56 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileView.swift
> +extension ProfileView { // data updates
Давай будем юзать //MARK: - Data update - и тд

2022-11-26 20:56 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileView.swift
>          self.userGroupLabel.text = with
поставь ` func updateUserGroup(with group: String)` и юзай внутри group

2022-11-26 20:56 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileView.swift
> +            // make.width.equalTo(100)
коменты убери

2022-11-26 20:56 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileViewController.swift
>          state = .auth
а лучше передавать из презентера

2022-11-26 21:02 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileView.swift
>          self.userGroupLabel.text = with
И давай все таки раздели по отдельным папкам все что связано с Auth и Profile

2022-11-26 21:23 UTC, Grandschtien requested changes

2022-11-26 21:23 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Application/Coordinators/AuthFlowCoordinator.swift
> +
Пробел убери

2022-11-26 21:23 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Application/Coordinators/AuthFlowCoordinator.swift
> +//        self.navigationController.setViewControllers([child.viewController], animated: false)
Коменты все убери подобные, ставь `//MARK:`

2022-11-26 21:23 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/Application/Coordinators/AuthFlowCoordinator.swift
> +//        self.navigationController.setViewControllers([child.viewController], animated: false)
И тоже не части с этим

2022-11-26 21:23 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/AuthView.swift
> +        bmstuImage.snp.makeConstraints { make in
Я так смотрю, тут вертикальные отступы одинаковые, мб юзнешь UIStackView?

2022-11-26 21:23 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/AuthView.swift
> +        bmstuImage.snp.makeConstraints { make in
И такой момент, лучше выносить UI приватные константы в файле класса, а так числа рандомными кажутся

2022-11-26 23:25 UTC, ArtemTin commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileView.swift
>          self.userGroupLabel.text = with
Может все-таки не стоит разделять? Просто в текущей реализации в папку Auth вынесется чисто только вьюшка, даже без контроллера

2022-11-27 14:19 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileCoordinator.swift
>      init(window: UIWindow, navigationController: UINavigationController) {
Суть просто в том, что координатор это штука которая запускает прилунений и выбирает сценарий, а роутеры делают навигацию между экранами

2022-11-27 14:22 UTC, Grandschtien requested changes

2022-11-27 14:22 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileProtocols.swift
> +protocol ProfileViewController: AnyObject {
Название поменяй, ставь в конце Protocol

2022-11-27 14:22 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileViewController.swift
> +        self.state = state
Давай все таки стейт будет определять презентер

2022-11-27 16:05 UTC, Grandschtien approved these changes

2022-11-27 16:05 UTC, merged