Flow changer
iOS-vk-education/2022_1s_ElectronicUniversity pull request #7
Opened 2022-12-06 14:25 UTC by ArtemTin

Переключение сценариев после первой авторизации (или отказа от нее). Создание таббара и т.п.

2022-12-06 14:29 UTC, Grandschtien requested changes

2022-12-06 14:29 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileRouter.swift
> +        let newFlow = MainFlowCoordinator.init(window: window,
Давай это вынесем в свойства класса, это зависимость

2022-12-06 17:10 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileBuilder.swift
> +        router.setMainFlowCoordinator(coordinator: MainFlowCoordinator(window: window,
А че ты его в инит не хочешь поставить?

2022-12-06 17:12 UTC, ArtemTin commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileBuilder.swift
> +        router.setMainFlowCoordinator(coordinator: MainFlowCoordinator(window: window,
тогда протокол не соблюдается

2022-12-08 13:01 UTC, Grandschtien approved these changes

2022-12-08 13:01 UTC, Grandschtien commented on Graal-BMSTU/Graal-BMSTU/ProfileScreen/ProfileBuilder.swift
> +        router.setMainFlowCoordinator(coordinator: MainFlowCoordinator(window: window,
У тебя инит в протоколе?

2022-12-08 13:01 UTC, merged